package com.arjun.samachar.utils

object StringsHelper {
    const val APP_NAME = "Samachar"
    const val LOADING = "loading"
    const val BACK_TO_TOP = "back to top"
    const val NO_DATA_FOUND = "No data found!"
    const val SELECT_NEWS_SOURCE = "Select News Source"
    const val BACK_BUTTON = "Back button"
    const val SEARCH_BUTTON = "Search button"
    const val LANGUAGE_BUTTON = "Language button"
    const val HEADLINE_IMAGE = "Headline image"
    const val NO_INTERNET_CONNECTION = "No internet connection!"
    const val CHOOSE_LANGUAGE = "Choose language"
    const val SELECT = "Select"
    const val RETRY = "Retry"
    const val DIALOG_ERROR_HEADER = "Error Occurred!"
    const val DIALOG_NETWORK_ERROR = "No internet connection. Try again later"
    const val TOAST_NETWORK_ERROR = "No internet connection"
    const val SAVED_TO_BOOKMARK = "Saved to bookmarks"
    const val REMOVED_FROM_BOOKMARKS = "Removed"
    const val BOOKMARKED_NEWS = "Bookmarks"
    const val OFFLINE_NEWS = "Offline mode"
    const val VIEW_NEWS_OFFLINE = "View News Offline"
}